version: 2.1

description: |
  A standard workflow for building images and pushing them to an ambassador container registry.

orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.2

commands:
  push-image:
    parameters:
      registry-url:
        type: string
        default: gcr.io
      google-project-id:
        description: The Google project ID to connect with via the gcloud CLI
        type: env_var_name
        default: GOOGLE_PROJECT_ID
      image:
        description: A name for your docker image
        type: string
      tag:
        description: A docker image tag
        type: string
        default: latest
    steps:
      - run:
          name: Push image to GCR
          command: |
            echo $GCP_KEY_FILE > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud --quiet beta auth configure-docker
            docker push <<parameters.registry-url>>/$<<parameters.google-project-id>>/<<parameters.image>>:<<parameters.tag>>

jobs:
  build_and_push:
    docker:
      - image: circleci/python:3.7.2
    shell: /bin/bash --login
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            echo "HELLO"
      - run:
          command: |
            echo "export CONTAINER_TAG=$CIRCLE_BRANCH-$(git rev-parse --short $CIRCLE_SHA1)" >> $BASH_ENV
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: $CIRCLE_PROJECT_REPONAME
          tag: $CONTAINER_TAG
      - push-image:
          image: $CIRCLE_PROJECT_REPONAME
          tag: $CONTAINER_TAG
